# Generated by Django 5.0.2 on 2024-02-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_rename_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Contact',
        ),
    ]
